CONCEPT_POLARITY = {
    # Positive financial/business signals
    "profit": 0.8,
    "growth": 0.7,
    "revenue": 0.6,
    "expansion": 0.6,
    "acquisition": 0.5,
    "confidence": 0.5,
    "investor confidence": 0.7,
    "demand": 0.4,
    "investment": 0.5,
    "profit growth": 0.9,
    "revenue growth": 0.8,
    "earnings growth": 0.8,
    "strong earnings": 0.8,
    "earnings": 0.6,
    "new market": 0.4,
    "new markets": 0.4,
    "market confidence": 0.6,
    

    # Negative financial/business signals
    "loss": -0.8,
    "decline": -0.7,
    "earnings decline": -0.9,
    "revenue decline": -0.8,
    "profit decline": -0.8,
    "risk": -0.5,
    "inflation": -0.4,
    "inflation risk": -0.7,
    "interest rate hike": -0.8,
    "layoff": -0.9,
    "layoffs": -0.9,
    "debt": -0.6,
    "uncertainty": -0.5,
    "pressure": -0.4,
    "regulatory pressure": -0.7,
    "slowdown": -0.6,
    "concern": -0.4,
    "concerns": -0.4,
    "market concern": -0.5,
    "market uncertainty": -0.7,
    "market volatility": -0.7,
    "economic slowdown": -0.8,
}